### ISSUE TITLE
执行提示 dial failed error=all DNS requests failed, first error no route to host

### ISSUE THREAD

**Issue by ysicing** [mritd/tpclash#12]
执行 `/usr/bin/tpclash -c /etc/clash/config.yaml --test --debug` 报错如下

```log
 dial failed error=all DNS requests failed, first error: Post "https://120.53.53.53/dns-query": dial tcp4 120.53.53.53:443: connect: no route to host
```

配置类似

```
mixed-port: 7890
# linux
tproxy-port: 7893
routing-mark: 7777
allow-lan: true
bind-address: "*"
mode: rule
log-level: info
interface-name: enp3s0
external-controller: 127.0.0.1:22222
secret: "666666666"
profile:
  store-selected: true
  store-fake-ip: true
  tracing: true
dns:
  enable: true
  listen: 0.0.0.0:1053
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  default-nameserver:
    - 121.4.4.123
    - 120.53.53.38
  nameserver:
    - https://doh.pub/dns-query
    - https://120.53.53.53/dns-query
    - https://1.12.12.12/dns-query
    - tls://dot.pub
    - https://dns.alidns.com/dns-query

tun:
  enable: true
  stack: system
  dns-hijack:
    - any:53
  auto-route: true
```
