### ISSUE TITLE
有办法绕过 ICMP DIG 等网络调试工具的流量吗？

### ISSUE THREAD

**Issue by yourxx** [mritd/tpclash#2]
有办法绕过 ICMP DIG 等网络调试工具的流量吗？

**Comment by mritd** [comment]
理论上添加适当的规则都可以跳过, 我后续尝试增加一些开关选项来绕过试试

**Comment by mritd** [comment]
已经添加了 `--hijack-dns` 选项用于指定劫持本机的

**Comment by mritd** [comment]
v.0.0.6 已经对本地流量和转发流量同时支持了 `--hijack-dns` 选项, 如果有问题请重新打开 issue.

**Comment by yourxx** [comment]
所以需要网络调试功能的话，还是得用 redir-host ， 我建议来几个选项：

- fake-ip
- redir-host
- 全自动设置代理

**Comment by yourxx** [comment]
我当网关用的，每次重启系统后，无法科学上网，不知道怎么排查，systemctl status tpclash 显示是正常的。systemctl restart tpclash 后就一切正常了。

**Comment by mritd** [comment]
重启后无法使用, 建议重启后 先不要重启 tpclash, 通过 iptables-save 保存一下 iptables 到文件; 然后可以发出来排查一下.

**Comment by yourxx** [comment]
MARK 改为 666 后重启也正常了。icmp 流量还没整明白。

```
root@tunnel:~# ping google.com
PING google.com (198.18.0.2) 56(84) bytes of data.
64 bytes from 198.18.0.2 (198.18.0.2): icmp_seq=1 ttl=64 time=0.033 ms
64 bytes from 198.18.0.2 (198.18.0.2): icmp_seq=2 ttl=64 time=0.052 ms
64 bytes from 198.18.0.2 (198.18.0.2): icmp_seq=3 ttl=64 time=0.046 ms
```

config.yaml
fake-ip-range: 198.18.0.0/16 还是 **fake-ip-range: 198.18.0.1/16**
```
mixed-port: 7890
redir-port: 7892
tproxy-port: 7893
allow-lan: true
bind-address: '*'
mode: rule
log-level: info
ipv6: false
external-controller: 0.0.0.0:9090
external-ui: dashboard
routing-mark: 666

profile:
  store-selected: true
  store-fake-ip: true

dns:
  enable: true
  listen: 0.0.0.0:1053
  ipv6: false
  enhanced-mode: fake-ip # redir-host or fake-ip
  fake-ip-range: 198.18.0.0/16
  fake-ip-filter:
    - '*.lan'
    - '*.local'
    - '+.ntp.*.*'
    - '+.stun.*.*'
    - '+.srv.nintendo.net'
    - '+.stun.playstation.net'
    - 'xbox.*.microsoft.com'
    - '+.xboxlive.com'
    - '.ipv6.microsoft.com'
    - 'localhost.ptlogin2.qq.com'
    - '+.msftconnecttest.com'
    - '+.msftncsi.com'
    - '+.nflxvideo.net'
    - '*.square-enix.com'
    - '*.finalfantasyxiv.com'
    - '*.ffxiv.com'
    - '*.mcdn.bilivideo.cn'
  use-hosts: true
  nameserver:
    - tls://223.5.5.5
  nameserver-policy:
    '+.taobao.com': '223.5.5.5'
    '+.qq.com': '119.29.29.29'
```

```
# Generated by iptables-save v1.8.7 on Mon Mar 14 13:41:43 2022
*mangle
:PREROUTING ACCEPT [0:0]
:INPUT ACCEPT [0:0]
:FORWARD ACCEPT [0:0]
:OUTPUT ACCEPT [0:0]
:POSTROUTING ACCEPT [0:0]
:TP_CLASH_LOCAL_V4 - [0:0]
:TP_CLASH_V4 - [0:0]
-A PREROUTING -j TP_CLASH_V4
-A OUTPUT -j TP_CLASH_LOCAL_V4
-A TP_CLASH_LOCAL_V4 -d 0.0.0.0/8 -j RETURN
-A TP_CLASH_LOCAL_V4 -d 127.0.0.0/8 -j RETURN
-A TP_CLASH_LOCAL_V4 -d 10.0.0.0/8 -j RETURN
-A TP_CLASH_LOCAL_V4 -d 172.16.0.0/12 -j RETURN
-A TP_CLASH_LOCAL_V4 -d 192.168.0.0/16 -j RETURN
-A TP_CLASH_LOCAL_V4 -d 169.254.0.0/16 -j RETURN
-A TP_CLASH_LOCAL_V4 -d 224.0.0.0/4 -j RETURN
-A TP_CLASH_LOCAL_V4 -d 240.0.0.0/4 -j RETURN
-A TP_CLASH_LOCAL_V4 -m owner --uid-owner 1000 -j RETURN
-A TP_CLASH_LOCAL_V4 -m owner --gid-owner 1001 -j RETURN
-A TP_CLASH_LOCAL_V4 -m owner --gid-owner 104 -j RETURN
-A TP_CLASH_LOCAL_V4 -p udp -m udp --dport 53 -j RETURN
-A TP_CLASH_LOCAL_V4 -p tcp -j MARK --set-xmark 0x29a/0xffffffff
-A TP_CLASH_LOCAL_V4 -p udp -j MARK --set-xmark 0x29a/0xffffffff
-A TP_CLASH_V4 -d 0.0.0.0/8 -j RETURN
-A TP_CLASH_V4 -d 127.0.0.0/8 -j RETURN
-A TP_CLASH_V4 -d 10.0.0.0/8 -j RETURN
-A TP_CLASH_V4 -d 172.16.0.0/12 -j RETURN
-A TP_CLASH_V4 -d 192.168.0.0/16 -j RETURN
-A TP_CLASH_V4 -d 169.254.0.0/16 -j RETURN
-A TP_CLASH_V4 -d 224.0.0.0/4 -j RETURN
-A TP_CLASH_V4 -d 240.0.0.0/4 -j RETURN
-A TP_CLASH_V4 -p udp -m udp --dport 53 -j RETURN
-A TP_CLASH_V4 -p tcp -j TPROXY --on-port 7893 --on-ip 0.0.0.0 --tproxy-mark 0x29a/0xffffffff
-A TP_CLASH_V4 -p udp -j TPROXY --on-port 7893 --on-ip 0.0.0.0 --tproxy-mark 0x29a/0xffffffff
COMMIT
# Completed on Mon Mar 14 13:41:43 2022
# Generated by iptables-save v1.8.7 on Mon Mar 14 13:41:43 2022
*nat
:PREROUTING ACCEPT [0:0]
:INPUT ACCEPT [0:0]
:OUTPUT ACCEPT [0:0]
:POSTROUTING ACCEPT [0:0]
:TP_CLASH_DNS_LOCAL_V4 - [0:0]
:TP_CLASH_DNS_V4 - [0:0]
-A PREROUTING -d 198.18.0.0/16 -p icmp -j DNAT --to-destination 127.0.0.1
-A PREROUTING -j TP_CLASH_DNS_V4
-A OUTPUT -d 198.18.0.0/16 -p icmp -j DNAT --to-destination 127.0.0.1
-A OUTPUT -j TP_CLASH_DNS_LOCAL_V4
-A TP_CLASH_DNS_LOCAL_V4 -m owner --uid-owner 1000 -j RETURN
-A TP_CLASH_DNS_LOCAL_V4 -m owner --gid-owner 1001 -j RETURN
-A TP_CLASH_DNS_LOCAL_V4 -m owner --gid-owner 104 -j RETURN
-A TP_CLASH_DNS_LOCAL_V4 -p udp -m udp --dport 53 -j REDIRECT --to-ports 1053
-A TP_CLASH_DNS_V4 -p udp -m udp --dport 53 -j REDIRECT --to-ports 1053
COMMIT
# Completed on Mon Mar 14 13:41:43 2022
```
