### ISSUE TITLE
关于转发失效的问题

### ISSUE THREAD

**Issue by elliot-bia** [mritd/tpclash#26]
环境：ubuntu 22.04 pve lxc 开启tun

问题描述：开启tpclash一段时间后作为网关无法转发流量（无iptables）

配置文件
```
mixed-port: 7890
allow-lan: true
bind-address: '*'
interface-name: eth0
mode: rule
log-level: info
external-controller: '127.0.0.1:9090'
profile:
  store-selected: true
  store-fake-ip: true
  tracing: true
# 请指定自己实际的接口名称(ip a 获取)

tun:
  enable: true
  stack: system
  dns-hijack:
    - any:53
  #   - 8.8.8.8:53
  #   - tcp://8.8.8.8:53
  # auto-route 与 ebpf 冲突, 不能同时使用
  #auto-route: true

# ebpf 需要指定物理网卡
ebpf:
  redirect-to-tun:
    - eth0

# ebpf 需要配置 mark
routing-mark: 666

dns:
    enable: true
    listen: 0.0.0.0:53
    ipv6: false
    default-nameserver: [223.5.5.5, 119.29.29.29]
    enhanced-mode: fake-ip
    fake-ip-range: 198.18.0.1/16

    nameserver:
        - https://doh.pub/dns-query
......
```

情景复现：下载tpclash后，使用[教程](https://ysicing.me/451/clash-gateway/)
无法转发流量，是不是iptables需要手撸？

**Comment by mritd** [comment]
`0.0.0.0:53` 换成 `0.0.0.0:1053` 试试, 然后 被代理机器的 DNS 填写 `223.5.5.5`(公网 DNS 都行).

**Comment by elliot-bia** [comment]
还是不行，日志如下：
```
2023-07-16 12:59:38 INFO [main] 🍄 提莫队长正在待命...
12:59:39 INF [TCP] connected lAddr=192.168.31.108:60744 rAddr=172.217.160.106:443 mode=rule rule=Match() proxy=DIRECT
12:59:42 WRN [TCP] dial failed error=dial tcp4 172.217.160.106:443: i/o timeout proxy=DIRECT lAddr=192.168.31.108:60743 rAddr=172.217.160.106:443 rule=Match rulePayload=
12:59:42 INF [TCP] connected lAddr=192.168.31.108:60762 rAddr=172.217.160.106:443 mode=rule rule=Match() proxy=DIRECT
12:59:44 WRN [TCP] dial failed error=dial tcp4 172.217.160.106:443: i/o timeout proxy=DIRECT lAddr=192.168.31.108:60746 rAddr=172.217.160.106:443 rule=Match rulePayload=
```

我是完全按照教程来的

**Comment by mritd** [comment]
这个日志看起来就是 DNS 没有被拦截, 你可以在被代理机器上测试一下 `dig baidu.com`, 正常应该返回 `198.18` 的 ip.

如果你的被代理机器是 windows, 需要关闭 ipv6.

**Comment by elliot-bia** [comment]
解析到198.18后也无法访问

复现环境：pve ubuntu 22.04
关闭`systemctl stop systemd-resolved && systemctl disable systemd-resolved`
使用tpclash-amd64, 命令`tpclash -c config.yaml`

配置内容：
```
 interface-name: ens18 # 请指定自己实际的接口名称(ip a 获取)

 port: 7890
 socks-port: 7891
 redir-port: 7892
 tproxy-port: 7893
 allow-lan: true
 bind-address: "*"
 mode: Rule
 log-level: info
 external-controller: 0.0.0.0:9090
 secret: ""

dns:
  enable: true
  ipv6: false
  listen: 0.0.0.0:1053
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  default-nameserver:
    - 114.114.114.114
    - 1.1.1.1
  nameserver:
      - https://doh.pub/dns-query
      - https://120.53.53.53/dns-query
      - https://1.12.12.12/dns-query
      - tls://dot.pub
      - tls://dns.alidns.com
      - https://dns.alidns.com/dns-query
      - https://dns.adguard.com/dns-query
      - tls://dns.adguard.com
      - https://doh.dns.sb/dns-query
      - tls://dot.sb
      - https://dns.twnic.tw/dns-query
  fake-ip-filter:
      - '*.lan'
      - 'time.*.com'
      - 'time.*.gov'
      - 'time.*.edu.cn'
      - 'time.*.apple.com'
      - 'ntp.*.com'
      - 'localhost.ptlogin2.qq.com'
      - '*.ntp.org.cn'
      - '+.pool.ntp.org'
      - '*.localhost'
  fallback:
      - https://doh.dns.sb/dns-query
      - https://dns.cloudflare.com/dns-query
      - https://dns.twnic.tw/dns-query
      - https://1.1.1.1/dns-query
      - tls://8.8.4.4:853
      - https://dns.google/dns-query
  fallback-filter:
      geoip: true
      geoip-code: CN
      ipcidr:
          - 240.0.0.0/4
          - 0.0.0.0/32
          - 127.0.0.1/32
          - 169.254.0.0/16
      domain:
          - '+.google.com'
          - '+.youtube.com'

 tun:
   enable: true
   stack: system
   auto-route: true
   auto-detect-interface: true
   dns-hijack:
     - any:53

proxies:
。。。
proxy-groups:
。。。

rule-providers:
。。。

rules:
    - 'DOMAIN-SUFFIX,local,DIRECT'
    - 'IP-CIDR,127.0.0.0/8,DIRECT'
    - 'IP-CIDR,172.16.0.0/12,DIRECT'
    - 'IP-CIDR,10.0.0.0/8,DIRECT'
    - 'IP-CIDR,17.0.0.0/8,DIRECT'
    - RULE-SET,applications,DIRECT
    - RULE-SET,private,DIRECT
    - RULE-SET,reject,REJECT
    - RULE-SET,icloud,DIRECT
    - RULE-SET,apple,DIRECT
    - RULE-SET,google,DIRECT
    - RULE-SET,direct,DIRECT
    - RULE-SET,lancidr,DIRECT
    - RULE-SET,cncidr,DIRECT
    - RULE-SET,proxy,PROXY
    - RULE-SET,telegramcidr,PROXY
    - GEOIP,LAN,DIRECT
    - 'DOMAIN-SUFFIX,cn,DIRECT'
    - 'DOMAIN-KEYWORD,-cn,DIRECT'
    - 'GEOIP,CN,DIRECT'
    - 'MATCH,DIRECT'

```
