### ISSUE TITLE
fake DNS是否生效问题

### ISSUE THREAD

**Issue by Wrandz** [mritd/tpclash#27]
感谢作者非常精彩的Clash DNS科普！这是少有的通俗且全面的讲解，能深入浅出把这个问题讲明白，确实有功底，厉害！

这里提一个我看完之后的问题：

clash作者的tun的配置是：
```
tun:
  enable: true
  stack: system # or gvisor
  # dns-hijack:
  #   - 8.8.8.8:53
  #   - tcp://8.8.8.8:53
  #   - any:53
  #   - tcp://any:53
  auto-route: true # manage `ip route` and `ip rules`
  auto-redir: true # manage nftable REDIRECT
  auto-detect-interface: true # conflict with `interface-name`
```
这里把 `dns-hijack`注释了，并且专门写明了`auto-route: true`, `auto-redir: true`, `auto-detect-interface: true`

而您这边给出的tun配置是：
```
tun:
  enable: true
  stack: system
  dns-hijack:
    - any:53
```
写明了 `dns-hijack`，但没有写`auto-route`, `auto-redir`, `auto-detect-interface`

我想问的是：

（1）是否【被代理主机使用公网dns，例如223.5.5.5:53的udp流量，到clash网关会被auto-route劫持】这个功能的实现，是因为 `dns-hijack`写明了劫持所有53端口的流量。如果像作者那样注释掉不写的话，是默认“劫持所有53端口的流量”还是说不写就不劫持？

（2）是否`auto-route`, `auto-redir`, `auto-detect-interface`这三个选项不写，就是默认true？因为我很疑惑，您提到劫持是通过auto-route 或 ebpf实现，但是不写，clash怎么知道是 auto-route 还是 ebpf 呢？

**Comment by Wrandz** [comment]
另外再补充一个我很早之前的疑惑。

在`fake dns`中，所有被代理主机的dns流量被劫持后，clash只是会返回一个假 DNS 结果。既然如此，clash的dns配置中
```
dns:
  enable: true
  listen: 0.0.0.0:1053
  ipv6: false
  default-nameserver:
    - 223.5.5.5
    - 119.29.29.29
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  nameserver:
    - 223.5.5.5
    - 119.29.29.29
```
`default-nameserver`和`nameserver`这两项还有什么用呢？我感觉这个只是在原来的redir-host模式还有用，在fake-ip模式应该没用了才对，没用了为啥还要设置？
