### ISSUE TITLE
配置了 wireguard 无法使用

### ISSUE THREAD

**Issue by 459217974** [mritd/tpclash#30]
配置如下：

```yaml
proxies:
  - name: "wg"
    type: wireguard
    server: ip
    port: 51820
    ip: 10.7.0.2
    private-key: kkkkkkk
    public-key: kkkkk
    remote-dns-resolve: true
    dns: [ip, ip]
    mtu: 1420
    udp: true
```
同样的配置在 clashx 客户端上是可以用的。
日志里显示能连上：
16:37:00 INF [UDP] connected lAddr=198.18.0.1:58973 rAddr=*.*.*.*:***** mode=rule rule=Match() proxy=PROXY[***]
报错：
WRN [TCP] dial failed error=dial: lookup www.slack.com. on *.*.*.*: write udp 10.7.0.2:27404: i/o timeout proxy=PROXY lAddr=192.168.2.8:47156 rAddr=www.slack.com:443 rule=RuleSet rulePayload=proxy

希望大佬可以帮忙分析一下为什么🙏
