### ISSUE TITLE
是否可以对安卓提供支持

### ISSUE THREAD

**Issue by SeeFlowerX** [mritd/tpclash#8]
主要出发点是想抓包

已经可以实现简单的抓包了，但是操作还挺麻烦的，我对iptables也是一头雾水

如果直接`iptables + clash转发 + 感觉会比较方便`

- https://blog.seeflower.dev/archives/207/

我尝试了这篇文章，[树莓派 Clash 透明代理(TProxy)](https://mritd.com/2022/02/06/clash-tproxy/)

流量已经到`clash`了，但是数据就是没有被转发到外部代理

还有就是安卓上没有useradd这些，所以默认在root下执行了

```yaml
# TProxy 的透明代理端口
tproxy-port: 7893

# mixed-port 端口将同时支持 SOCKS5/HTTP
mixed-port: 7890

# RESTful API for clash
external-controller: 127.0.0.1:9090

allow-lan: true

mode: global

log-level: debug

bind-address: 0.0.0.0

dns:
    enable: true
    listen: 0.0.0.0:1053
    ipv6: true
    enhanced-mode: fake-ip
    nameserver:
      - 114.114.114.114

proxies:
  - name: "charles"
    type: socks5
    server: 192.168.1.10
    port: 18889
    udp: true
    
proxy-groups:

rules:

```
